# Generated by Django 5.2.5 on 2025-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المنتج')),
                ('followers_count', models.IntegerField(blank=True, null=True, verbose_name='عدد المتابعين')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر المنتج')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='لون المنتج')),
                ('category', models.CharField(blank=True, max_length=150, null=True, verbose_name='تصنيف المنتج')),
                ('product_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المنتج')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة 4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
